### ISSUE TITLE
Geostyler package will not build when following documentation.

### ISSUE THREAD

**Issue by lstillwe** [geostyler/geostyler#2489]
### Question

Please help - I am struggling with getting geostyler to work.
I am running npm version: 10.5.0 and node version: v20.12.0 
I tried to add the geostyler library to a brand new react project created like this:
`npx create-react-app style-app`

According to the geostyler documentation ...
I installed geostyler like this:
```
npm i geostyler
npm i geostyler-sld-parser
```

Then I made my App.js look like this:
```
import './App.css';
import { Style } from 'geostyler';

const App = () => {

  const onStyleChange = (geostylerStyle) => {
    console.log('New GeoStyler style ', geostylerStyle);
  };

  return (
    <Style
      onStyleChange={onStyleChange}
    />
  );
};
```

And when I run npm start, I get the following errors:

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 630:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 630:51-70
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 657:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 657:51-70
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 661:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 661:58-77
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 710:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 710:51-70
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 733:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 733:51-70
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 737:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 737:57-76
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 741:9-28
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 829:37-56
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 841:37-56
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 844:38-57
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 869:15-34
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/dist/QGISStyleParser.js 869:65-84
export 'isGeoStylerFunction' (imported as 'isGeoStylerFunction') was not found in 'geostyler-style' (module has no exports)

ERROR in ./node_modules/geostyler-qgis-parser/node_modules/geostyler-cql-parser/dist/CqlParser.js 1:0-92
Module not found: Error: Can't resolve 'geostyler-style/dist/typeguards' in '/Users/lisa/style-app/node_modules/geostyler-qgis-parser/node_modules/geostyler-cql-parser/dist'
Did you mean 'typeguards.js'?
BREAKING CHANGE: The request 'geostyler-style/dist/typeguards' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler-qgis-parser/node_modules/geostyler-style/dist/index.js 1:0-24
Module not found: Error: Can't resolve './style' in '/Users/lisa/style-app/node_modules/geostyler-qgis-parser/node_modules/geostyler-style/dist'
Did you mean 'style.js'?
BREAKING CHANGE: The request './style' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler-qgis-parser/node_modules/geostyler-style/dist/index.js 2:0-28
Module not found: Error: Can't resolve './functions' in '/Users/lisa/style-app/node_modules/geostyler-qgis-parser/node_modules/geostyler-style/dist'
Did you mean 'functions.js'?
BREAKING CHANGE: The request './functions' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler-qgis-parser/node_modules/geostyler-style/dist/index.js 3:0-29
Module not found: Error: Can't resolve './typeguards' in '/Users/lisa/style-app/node_modules/geostyler-qgis-parser/node_modules/geostyler-style/dist'
Did you mean 'typeguards.js'?
BREAKING CHANGE: The request './typeguards' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

**Comment by jansule** [comment]
@hwbllmnn could you take a look at this? Sounds like there might be some config missing.

**Comment by KaiVolland** [comment]
This should be fixed with the upcoming major release of geostyler.

**Comment by hwbllmnn** [comment]
What bundler is the created project using? In case it's using webpack, have a look at https://gist.github.com/hwbllmnn/52fcc5c860528c94227f5b51a9833b01 for a snippet of config that should fix the issue.

**Comment by hwbllmnn** [comment]
BTW, for now you can also try to either downgrade the sld-parser to `5.4.0` or update geostyler to `15.0.0-beta.4`.

**Comment by lstillwe** [comment]
I tried upgrading to geostyler 15.0.0-beta.4, and that did not work.
I also added the rule and resolve snippets (for web pack) provided in the weblink snippets. and that did not resolve the problem. 
Here are my package.json, webpack.config.js, and App.js files ...

[package.json](https://github.com/user-attachments/files/16072934/package.json)
[webpack.config.js.txt](https://github.com/user-attachments/files/16072967/webpack.config.js.txt)
[App.js.txt](https://github.com/user-attachments/files/16072958/App.js.txt)

And these are the current ERRORS: 
`Failed to compile.

Attempted import error: 'Style' is not exported from 'geostyler' (imported as 'Style').
WARNING in [eslint] 
src/App.js
  Line 1:8:  'logo' is defined but never used  no-unused-vars

ERROR in ./src/App.js 12:30-35
export 'Style' (imported as 'Style') was not found in 'geostyler' (possible exports: ConfigProvider, locale)

ERROR in ./node_modules/geostyler/dist/index.js 29:0-82
Module not found: Error: Can't resolve './Component/Filter/AttributeCombo/AttributeCombo' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'AttributeCombo.js'?
BREAKING CHANGE: The request './Component/Filter/AttributeCombo/AttributeCombo' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 30:0-85
Module not found: Error: Can't resolve './Component/Filter/BoolFilterField/BoolFilterField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'BoolFilterField.js'?
BREAKING CHANGE: The request './Component/Filter/BoolFilterField/BoolFilterField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 31:0-63
Module not found: Error: Can't resolve './Component/Breadcrumb/Breadcrumb' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Breadcrumb.js'?
BREAKING CHANGE: The request './Component/Breadcrumb/Breadcrumb' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 32:0-95
Module not found: Error: Can't resolve './Component/Symbolizer/Field/BrightnessField/BrightnessField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'BrightnessField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/BrightnessField/BrightnessField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 33:0-86
Module not found: Error: Can't resolve './Component/Symbolizer/BulkEditModals/BulkEditModals' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'BulkEditModals.js'?
BREAKING CHANGE: The request './Component/Symbolizer/BulkEditModals/BulkEditModals' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 34:0-63
Module not found: Error: Can't resolve './Component/BulkEditor/BulkEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'BulkEditor.js'?
BREAKING CHANGE: The request './Component/BulkEditor/BulkEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 35:0-60
Module not found: Error: Can't resolve './Component/CardStyle/CardStyle' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'CardStyle.js'?
BREAKING CHANGE: The request './Component/CardStyle/CardStyle' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 36:0-86
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ChannelField/ChannelField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ChannelField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ChannelField/ChannelField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 37:0-113
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ChannelSelectionField/ChannelSelectionField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ChannelSelectionField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ChannelSelectionField/ChannelSelectionField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 38:0-63
Module not found: Error: Can't resolve './Component/CodeEditor/CodeEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'CodeEditor.js'?
BREAKING CHANGE: The request './Component/CodeEditor/CodeEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 39:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ColorField/ColorField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ColorField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ColorField/ColorField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 40:0-86
Module not found: Error: Can't resolve './Component/Symbolizer/ColorMapEditor/ColorMapEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ColorMapEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/ColorMapEditor/ColorMapEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 41:0-104
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ColorMapEntryField/ColorMapEntryField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ColorMapEntryField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ColorMapEntryField/ColorMapEntryField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 42:0-101
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ColorMapTypeField/ColorMapTypeField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ColorMapTypeField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ColorMapTypeField/ColorMapTypeField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 43:0-89
Module not found: Error: Can't resolve './Component/RuleGenerator/ColorRampCombo/ColorRampCombo' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ColorRampCombo.js'?
BREAKING CHANGE: The request './Component/RuleGenerator/ColorRampCombo/ColorRampCombo' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 44:0-88
Module not found: Error: Can't resolve './Component/Filter/ComparisonFilter/ComparisonFilter' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ComparisonFilter.js'?
BREAKING CHANGE: The request './Component/Filter/ComparisonFilter/ComparisonFilter' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 45:0-122
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ContrastEnhancementField/ContrastEnhancementField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ContrastEnhancementField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ContrastEnhancementField/ContrastEnhancementField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 46:0-89
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ContrastField/ContrastField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ContrastField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ContrastField/ContrastField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 47:0-73
Module not found: Error: Can't resolve './Component/DataInput/DataLoader/DataLoader' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'DataLoader.js'?
BREAKING CHANGE: The request './Component/DataInput/DataLoader/DataLoader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 48:0-62
Module not found: Error: Can't resolve './Component/Symbolizer/Editor/Editor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Editor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Editor/Editor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 49:0-89
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ExtendedField/ExtendedField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ExtendedField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ExtendedField/ExtendedField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 50:0-101
Module not found: Error: Can't resolve './Component/Symbolizer/Field/FadeDurationField/FadeDurationField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FadeDurationField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/FadeDurationField/FadeDurationField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 51:0-57
Module not found: Error: Can't resolve './Component/FieldSet/FieldSet' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FieldSet.js'?
BREAKING CHANGE: The request './Component/FieldSet/FieldSet' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 52:0-75
Module not found: Error: Can't resolve './Component/FieldContainer/FieldContainer' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FieldContainer.js'?
BREAKING CHANGE: The request './Component/FieldContainer/FieldContainer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 53:0-74
Module not found: Error: Can't resolve './Component/Symbolizer/FillEditor/FillEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FillEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/FillEditor/FillEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 54:0-94
Module not found: Error: Can't resolve './Component/Filter/FilterEditorWindow/FilterEditorWindow' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FilterEditorWindow.js'?
BREAKING CHANGE: The request './Component/Filter/FilterEditorWindow/FilterEditorWindow' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 55:0-75
Module not found: Error: Can't resolve './Component/FilterOverview/FilterOverview' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FilterOverview.js'?
BREAKING CHANGE: The request './Component/FilterOverview/FilterOverview' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 56:0-70
Module not found: Error: Can't resolve './Component/Filter/FilterTree/FilterTree' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FilterTree.js'?
BREAKING CHANGE: The request './Component/Filter/FilterTree/FilterTree' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 57:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/Field/FontPicker/FontPicker' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FontPicker.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/FontPicker/FontPicker' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 58:0-63
Module not found: Error: Can't resolve './Component/FunctionUI/FunctionUI' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'FunctionUI.js'?
BREAKING CHANGE: The request './Component/FunctionUI/FunctionUI' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 59:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/Field/GammaField/GammaField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'GammaField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/GammaField/GammaField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 60:0-83
Module not found: Error: Can't resolve './Component/Symbolizer/GraphicEditor/GraphicEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'GraphicEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/GraphicEditor/GraphicEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 61:0-98
Module not found: Error: Can't resolve './Component/Symbolizer/Field/GraphicTypeField/GraphicTypeField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'GraphicTypeField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/GraphicTypeField/GraphicTypeField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 62:0-98
Module not found: Error: Can't resolve './Component/Symbolizer/Field/GrayChannelField/GrayChannelField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'GrayChannelField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/GrayChannelField/GrayChannelField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 63:0-74
Module not found: Error: Can't resolve './Component/Symbolizer/IconEditor/IconEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'IconEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/IconEditor/IconEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 64:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/IconSelector/IconSelector' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'IconSelector.js'?
BREAKING CHANGE: The request './Component/Symbolizer/IconSelector/IconSelector' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 65:0-98
Module not found: Error: Can't resolve './Component/Symbolizer/IconSelectorWindow/IconSelectorWindow' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'IconSelectorWindow.js'?
BREAKING CHANGE: The request './Component/Symbolizer/IconSelectorWindow/IconSelectorWindow' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 66:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ImageField/ImageField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ImageField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ImageField/ImageField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 67:0-77
Module not found: Error: Can't resolve './Component/Symbolizer/Field/KindField/KindField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'KindField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/KindField/KindField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 68:0-86
Module not found: Error: Can't resolve './Component/Symbolizer/Field/LineCapField/LineCapField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'LineCapField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/LineCapField/LineCapField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 69:0-89
Module not found: Error: Can't resolve './Component/Symbolizer/Field/LineDashField/LineDashField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'LineDashField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/LineDashField/LineDashField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 70:0-74
Module not found: Error: Can't resolve './Component/Symbolizer/LineEditor/LineEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'LineEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/LineEditor/LineEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 71:0-89
Module not found: Error: Can't resolve './Component/Symbolizer/Field/LineJoinField/LineJoinField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'LineJoinField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/LineJoinField/LineJoinField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 72:0-74
Module not found: Error: Can't resolve './Component/Symbolizer/MarkEditor/MarkEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'MarkEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/MarkEditor/MarkEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 73:0-87
Module not found: Error: Can't resolve './Component/ScaleDenominator/MaxScaleDenominator' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'MaxScaleDenominator.js'?
BREAKING CHANGE: The request './Component/ScaleDenominator/MaxScaleDenominator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 74:0-87
Module not found: Error: Can't resolve './Component/ScaleDenominator/MinScaleDenominator' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'MinScaleDenominator.js'?
BREAKING CHANGE: The request './Component/ScaleDenominator/MinScaleDenominator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 75:0-77
Module not found: Error: Can't resolve './Component/Symbolizer/MultiEditor/MultiEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'MultiEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/MultiEditor/MultiEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 76:0-60
Module not found: Error: Can't resolve './Component/NameField/NameField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'NameField.js'?
BREAKING CHANGE: The request './Component/NameField/NameField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 77:0-91
Module not found: Error: Can't resolve './Component/Filter/NumberFilterField/NumberFilterField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'NumberFilterField.js'?
BREAKING CHANGE: The request './Component/Filter/NumberFilterField/NumberFilterField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 78:0-83
Module not found: Error: Can't resolve './Component/Symbolizer/Field/OffsetField/OffsetField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'OffsetField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/OffsetField/OffsetField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 79:0-86
Module not found: Error: Can't resolve './Component/Symbolizer/Field/OpacityField/OpacityField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'OpacityField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/OpacityField/OpacityField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 80:0-79
Module not found: Error: Can't resolve './Component/Filter/OperatorCombo/OperatorCombo' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'OperatorCombo.js'?
BREAKING CHANGE: The request './Component/Filter/OperatorCombo/OperatorCombo' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 81:0-63
Module not found: Error: Can't resolve './Component/PreviewMap/PreviewMap' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'PreviewMap.js'?
BREAKING CHANGE: The request './Component/PreviewMap/PreviewMap' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 82:0-86
Module not found: Error: Can't resolve './Component/Symbolizer/PropTextEditor/PropTextEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'PropTextEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/PropTextEditor/PropTextEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 83:0-83
Module not found: Error: Can't resolve './Component/Symbolizer/Field/RadiusField/RadiusField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RadiusField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/RadiusField/RadiusField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 84:0-101
Module not found: Error: Can't resolve './Component/Symbolizer/RasterChannelEditor/RasterChannelEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RasterChannelEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/RasterChannelEditor/RasterChannelEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 85:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/RasterEditor/RasterEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RasterEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/RasterEditor/RasterEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 86:0-72
Module not found: Error: Can't resolve './Component/RemovableItem/RemovableItem' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RemovableItem.js'?
BREAKING CHANGE: The request './Component/RemovableItem/RemovableItem' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 87:0-72
Module not found: Error: Can't resolve './Component/Renderer/OlRenderer/OlRenderer' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'OlRenderer.js'?
BREAKING CHANGE: The request './Component/Renderer/OlRenderer/OlRenderer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 88:0-66
Module not found: Error: Can't resolve './Component/Renderer/Renderer/Renderer' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Renderer.js'?
BREAKING CHANGE: The request './Component/Renderer/Renderer/Renderer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 89:0-95
Module not found: Error: Can't resolve './Component/Symbolizer/Field/RgbChannelField/RgbChannelField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RgbChannelField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/RgbChannelField/RgbChannelField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 90:0-95
Module not found: Error: Can't resolve './Component/Symbolizer/Field/ResamplingField/ResamplingField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ResamplingField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/ResamplingField/ResamplingField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 91:0-83
Module not found: Error: Can't resolve './Component/Symbolizer/Field/RotateField/RotateField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RotateField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/RotateField/RotateField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 92:0-57
Module not found: Error: Can't resolve './Component/RuleCard/RuleCard' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RuleCard.js'?
BREAKING CHANGE: The request './Component/RuleCard/RuleCard' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 93:0-87
Module not found: Error: Can't resolve './Component/RuleFieldContainer/RuleFieldContainer' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RuleFieldContainer.js'?
BREAKING CHANGE: The request './Component/RuleFieldContainer/RuleFieldContainer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 94:0-72
Module not found: Error: Can't resolve './Component/RuleGenerator/RuleGenerator' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RuleGenerator.js'?
BREAKING CHANGE: The request './Component/RuleGenerator/RuleGenerator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 95:0-84
Module not found: Error: Can't resolve './Component/RuleGenerator/RuleGeneratorWindow' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RuleGeneratorWindow.js'?
BREAKING CHANGE: The request './Component/RuleGenerator/RuleGeneratorWindow' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 96:0-69
Module not found: Error: Can't resolve './Component/RuleOverview/RuleOverview' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RuleOverview.js'?
BREAKING CHANGE: The request './Component/RuleOverview/RuleOverview' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 97:0-48
Module not found: Error: Can't resolve './Component/Rules/Rules' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Rules.js'?
BREAKING CHANGE: The request './Component/Rules/Rules' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 98:0-60
Module not found: Error: Can't resolve './Component/RuleTable/RuleTable' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'RuleTable.js'?
BREAKING CHANGE: The request './Component/RuleTable/RuleTable' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 99:0-95
Module not found: Error: Can't resolve './Component/Symbolizer/Field/SaturationField/SaturationField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SaturationField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/SaturationField/SaturationField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 100:0-81
Module not found: Error: Can't resolve './Component/ScaleDenominator/ScaleDenominator' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'ScaleDenominator.js'?
BREAKING CHANGE: The request './Component/ScaleDenominator/ScaleDenominator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 101:0-63
Module not found: Error: Can't resolve './Component/Selectable/Selectable' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Selectable.js'?
BREAKING CHANGE: The request './Component/Selectable/Selectable' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 102:0-86
Module not found: Error: Can't resolve './Component/Selectable/SelectableItem/SelectableItem' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SelectableItem.js'?
BREAKING CHANGE: The request './Component/Selectable/SelectableItem/SelectableItem' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 103:0-77
Module not found: Error: Can't resolve './Component/Symbolizer/Field/SizeField/SizeField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SizeField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/SizeField/SizeField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 104:0-69
Module not found: Error: Can't resolve './Component/SortableItem/SortableItem' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SortableItem.js'?
BREAKING CHANGE: The request './Component/SortableItem/SortableItem' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 105:0-75
Module not found: Error: Can't resolve './Component/Renderer/SLDRenderer/SLDRenderer' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SLDRenderer.js'?
BREAKING CHANGE: The request './Component/Renderer/SLDRenderer/SLDRenderer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 106:0-116
Module not found: Error: Can't resolve './Component/Symbolizer/Field/SourceChannelNameField/SourceChannelNameField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SourceChannelNameField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/SourceChannelNameField/SourceChannelNameField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 107:0-48
Module not found: Error: Can't resolve './Component/Style/Style' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Style.js'?
BREAKING CHANGE: The request './Component/Style/Style' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 108:0-90
Module not found: Error: Can't resolve './Component/StyleFieldContainer/StyleFieldContainer' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'StyleFieldContainer.js'?
BREAKING CHANGE: The request './Component/StyleFieldContainer/StyleFieldContainer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 109:0-76
Module not found: Error: Can't resolve './Component/DataInput/StyleLoader/StyleLoader' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'StyleLoader.js'?
BREAKING CHANGE: The request './Component/DataInput/StyleLoader/StyleLoader' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 110:0-72
Module not found: Error: Can't resolve './Component/StyleOverview/StyleOverview' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'StyleOverview.js'?
BREAKING CHANGE: The request './Component/StyleOverview/StyleOverview' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 111:0-75
Module not found: Error: Can't resolve './Component/SymbolizerCard/SymbolizerCard' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SymbolizerCard.js'?
BREAKING CHANGE: The request './Component/SymbolizerCard/SymbolizerCard' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 112:0-110
Module not found: Error: Can't resolve './Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'SymbolizerEditorWindow.js'?
BREAKING CHANGE: The request './Component/Symbolizer/SymbolizerEditorWindow/SymbolizerEditorWindow' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 113:0-66
Module not found: Error: Can't resolve './Component/Symbolizers/Symbolizers' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'Symbolizers.js'?
BREAKING CHANGE: The request './Component/Symbolizers/Symbolizers' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 114:0-74
Module not found: Error: Can't resolve './Component/Symbolizer/TextEditor/TextEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'TextEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/TextEditor/TextEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 115:0-85
Module not found: Error: Can't resolve './Component/Filter/TextFilterField/TextFilterField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'TextFilterField.js'?
BREAKING CHANGE: The request './Component/Filter/TextFilterField/TextFilterField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 116:0-69
Module not found: Error: Can't resolve './Component/UploadButton/UploadButton' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'UploadButton.js'?
BREAKING CHANGE: The request './Component/UploadButton/UploadButton' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 117:0-101
Module not found: Error: Can't resolve './Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'WellKnownNameEditor.js'?
BREAKING CHANGE: The request './Component/Symbolizer/WellKnownNameEditor/WellKnownNameEditor' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 118:0-104
Module not found: Error: Can't resolve './Component/Symbolizer/Field/WellKnownNameField/WellKnownNameField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'WellKnownNameField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/WellKnownNameField/WellKnownNameField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 119:0-80
Module not found: Error: Can't resolve './Component/Symbolizer/Field/WidthField/WidthField' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'WidthField.js'?
BREAKING CHANGE: The request './Component/Symbolizer/Field/WidthField/WidthField' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 120:0-79
Module not found: Error: Can't resolve './context/GeoStylerContext/GeoStylerContext' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'GeoStylerContext.js'?
BREAKING CHANGE: The request './context/GeoStylerContext/GeoStylerContext' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 122:0-35
Module not found: Error: Can't resolve './locale/de_DE' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'de_DE.js'?
BREAKING CHANGE: The request './locale/de_DE' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 123:0-35
Module not found: Error: Can't resolve './locale/en_US' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'en_US.js'?
BREAKING CHANGE: The request './locale/en_US' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 124:0-35
Module not found: Error: Can't resolve './locale/es_ES' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'es_ES.js'?
BREAKING CHANGE: The request './locale/es_ES' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 125:0-35
Module not found: Error: Can't resolve './locale/fr_FR' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'fr_FR.js'?
BREAKING CHANGE: The request './locale/fr_FR' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/geostyler/dist/index.js 126:0-35
Module not found: Error: Can't resolve './locale/zh_CN' in '/Users/lisa/style-app/node_modules/geostyler/dist'
Did you mean 'zh_CN.js'?
BREAKING CHANGE: The request './locale/zh_CN' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 98 errors and 1 warning`

**Comment by hwbllmnn** [comment]
Looks like our approach using `create-react-app` isn't working any more. Try this:

```shell
npm create vite:latest
```

Specify `react` as the framework and `typescript` as the variant. Then you can use the same approach (install geostyler, adapt the `App.tsx`) to get started. I still recommend using the beta version of GeoStyler. Also, install less using `npm i -D less`. Using that approach I can run the dev mode and build the app with no problems, but you'll probably need to tweak the css a bit, the ui doesn't seem to be properly usable with your app code out of the box.
